[theme]
primaryColor = "#A2AD91" # Light Sage for sliders/accents
backgroundColor = "#3B3F30" # Dark Olive Green
secondaryBackgroundColor = "#4B5320" # Army Green for Sidebar/Cards
textColor = "#F5F5DC" # Cream/Beige for text (highly visible)
font = "serif"
